### ISSUE TITLE
 Change server repositories to GitHub Pages

### ISSUE THREAD

**Issue by WGzeyu** [Zingabopp/BeatSaberMultiplayer#17]
It is recommended to enable GitHub Pages for https://github.com/Zingabopp/BeatSaberMultiplayerServerRepo and change the server repositories to GitHub Pages.
I observed that during the peak period, China Telecom could hardly load the page from raw.githubusercontent.com, but github.io could work normally.

**Comment by WGzeyu** [comment]
Is it possible to enable Github Pages for the server repository and set it as the default?
During this period of time, quite a few China Telecom users were unable to load the server list. However, they can connect to github.io normally.
If switch it to Github Pages, it will solve this problem very well, and the files will also be synchronized with GitHub.
(For example, I made a Mod list translation [wgzeyu/ModAssistant-CN](https://github.com/wgzeyu/ModAssistant-CN), using raw.githubusercontent.com, there are also quite a lot of China Telecom users failed to load, but after I changed it to github.io, no user encountered this problem.)

**Comment by Zingabopp** [comment]
Should be working, is this good? https://zingabopp.github.io/BeatSaberMultiplayerServerRepo/CompatibleServers.json

**Comment by WGzeyu** [comment]
It works fine
https://www.boce.com/http_raw.githubusercontent.com_fd2c690a82b0526664a8ff6a2298ea74.html
https://www.boce.com/http_zingabopp.github.io_b7b169b9e376b5b6756380f17225a71f.html
This is a comparison of the two addresses visited in China. 
I just tested it and found that a large percentage of raw.githubusercontent.com was resolved to 127.0.0.1 (but it did not appear in my case)

**Comment by Zingabopp** [comment]
Next version of Multiplayer Lite will use the new URL. I also made a PR to Andruzz's Multiplayer. Until then, players will have to change the URL manually in their config files.
