### ISSUE TITLE
The lobby just freaks out randomly

### ISSUE THREAD

**Issue by EitanGITHUB** [Zingabopp/BeatSaberMultiplayer#18]
After one or more songs the lobby starts freaking out, it starts doing stuff such as: not letting you go back to the main menu of beat saber (and you need to restart your game every time it happens and trust me, it happens a lot), it gets stuck on one song and it doesnt switch songs when the host puts a new song (happens when you are not host).

**Comment by Zingabopp** [comment]
Probably related to the ScoreSaber issue. A workaround is in the next build.

**Comment by EitanGITHUB** [comment]
I don't think it's related to score saber, but if you can fix it I'll be
more then happy
