### ISSUE TITLE
This getting updated to support new Beat Saber?

### ISSUE THREAD

**Issue by Axsgranted** [Zingabopp/BeatSaberMultiplayer#41]
While the updated beat saber supports multiplayer built-in, it ONLY supports non-custom songs which severely limits it's usefulness.

**Comment by Zingabopp** [comment]
Probably not, there are better things being worked on that integrate with the multiplayer code in the game.

**Comment by Axsgranted** [comment]
Anything out yet? :)

**Comment by Zingabopp** [comment]
<https://github.com/Zingabopp/MultiplayerExtensions>

**Comment by helix4u** [comment]
any plans for the extensions to allow for players in multiplayer to choose different difficulties? This would make playing with my friends a lot more enjoyable for both of us as I'm just starting out and he's very experienced, so we always have to try and find a compromise on difficulty.

**Comment by Zingabopp** [comment]
Feature requests for MultiplayerExtensions should be made directly on the MultiplayerExtensions repository.
