### ISSUE TITLE
Pausing in a match causes some notes to dissappear for the rest of the match

### ISSUE THREAD

**Issue by megalon** [Zingabopp/BeatSaberMultiplayer#6]
I'm not sure if you are aware of this issue because I don't see it posted here and a quick search of "pause" in the #multiplayer channel in BSMG didn't show any relevant results.

Last night I was watching phoenixin and when they paused the game in multiplayer, the notes turned into "rabbit notes" for a few beats, then notes started randomly disappearing.

Here is the clip
<https://clips.twitch.tv/NurturingAggressiveTarsierTooSpicy>

Here is what that section is supposed to look like
<https://youtu.be/I5cEUdSFwYk?t=82>

Looks like they were using 7.0.3, and I'm not sure if this issue exists in the current 7.0.4-L release

**Comment by Zingabopp** [comment]
That's interesting, I'll look into it. I doubt 7.0.4 would've fixed it.

**Comment by Zingabopp** [comment]
This seems to not be an issue anymore.
