### ISSUE TITLE
How do i setup a ServerHub?

### ISSUE THREAD

**Issue by JBSTheGamer** [Zingabopp/BeatSaberMultiplayer#7]
So when i downloaded the server hub i have configured the settings of it. I have also port forwarded the server hub port in my router settings. When i go check to see if the port is port forwarding it says its not. The WebSocketServer is also being port forwarded and that one works when i test to see if its port forwarding. I have a windows 10 Pro 64-Bit OS. So i downloaded the ServerHub_7.1.0_win-64. So i know i don't have the wrong one.
Below is the WebSocketPort working.
![2020 01 23-13 03](https://user-images.githubusercontent.com/32559193/73015086-0213a800-3de1-11ea-82de-ddabc529c9f6.png)
Below is the ServerHub Port not working.
![2020 01 23-13 04](https://user-images.githubusercontent.com/32559193/73015110-0fc92d80-3de1-11ea-8aec-895bcca858a4.png)
Below here is what my console is.
![2020 01 23-13 06_01](https://user-images.githubusercontent.com/32559193/73015241-4606ad00-3de1-11ea-9e19-6e1e917e8ba1.png)
As you can see below i am port forwarding both ports but only one works. The only one that is not working is the ServerHub port which is 3800. However the other port of 3701 is working for the WebSocketServer as you saw above.
![2020 01 23-13 07](https://user-images.githubusercontent.com/32559193/73015475-b7def680-3de1-11ea-8f9a-10625e5c172a.png)
Is there anything else i'm missing? I just cant seem to get it working for the ServerHub Port. Your probably going to ask for the Settings.json file so here it is.
[Settings.zip](https://github.com/Zingabopp/BeatSaberMultiplayer/files/4104988/Settings.zip)

**Comment by Zingabopp** [comment]
Did you have the Multiplayer mod configured properly to connect to your server? Your port isn't the default of 3700, so you have to make sure the mod connects to that port. I did see your server briefly in the list, but it seems to be down now. For the port tester, the ServerHub might not respond to it, so that might be normal?

**Comment by JBSTheGamer** [comment]
ok i will try default port of 3700 and then i will port forward it.

**Comment by JBSTheGamer** [comment]
ok i did that

**Comment by JBSTheGamer** [comment]
That is what it said by the way.
![2020 01 23-13 24](https://user-images.githubusercontent.com/32559193/73016716-04c3cc80-3de4-11ea-9d2c-ccc121a61c49.png)

**Comment by JBSTheGamer** [comment]
Ok so i have set the port to the default of 3700. I have also changed the last port in my router which was 3800 before but now i changed it to 3700. So now im port forwarding 3700. And the console also says hosting server hub on port 3700.

**Comment by JBSTheGamer** [comment]
So is it working now?

**Comment by JBSTheGamer** [comment]
So i have set the ServerHub Port to the default of 3700 in the settings.json file. Then i changed it from 3800 to port 3700 to port forward now.
![2020 01 23-13 35_01](https://user-images.githubusercontent.com/32559193/73017396-620c4d80-3de5-11ea-8608-ac1b5c779444.png)

**Comment by WGzeyu** [comment]
ServerHub uses UDP and only listens on the UDP port, while Port Tester is the TCP port for testing, so it will report port closed

**Comment by JBSTheGamer** [comment]
Ok so should i set the ServerHub port which is 3700 to UDP only? Right now its TCP and UDP.

**Comment by JBSTheGamer** [comment]
Also if i were to give the IP and Port to someone do i send them my public IP? I would think to send that one, am i right? I don't know as i never used this before.

**Comment by WGzeyu** [comment]
> Ok so should i set the ServerHub port which is 3700 to UDP only? Right now its TCP and UDP.

Only UDP or TCP + UDP can be used as long as UDP is included.



> Also if i were to give the IP and Port to someone do i send them my public IP? I would think to send that one, am i right? I don't know as i never used this before.

If you need to send your IP and port, then you must use your public IP.

**Comment by JBSTheGamer** [comment]
ok thanks

**Comment by JBSTheGamer** [comment]
So i saw you tried connecting and did it work? Now that i set the port back to default.
![2020 01 24-11 47](https://user-images.githubusercontent.com/32559193/73091156-6dbc4a80-3e9f-11ea-8787-bada5f8f2557.png)

**Comment by Zingabopp** [comment]
I think it'll say that anytime someone has your serverhub in their config when they go into the room list. Looks like it's working.

**Comment by JBSTheGamer** [comment]
okay so its working?

**Comment by JBSTheGamer** [comment]
well for you?

**Comment by Zingabopp** [comment]
Yep, want me to add you to the ServerRepo so other people can see your server easily?

**Comment by JBSTheGamer** [comment]
yes please

**Comment by JBSTheGamer** [comment]
I mainly keep my computer on 24/7. So the server will be rarely down.

**Comment by Zingabopp** [comment]
You're added, let me know if you want it removed/changed here: https://github.com/Zingabopp/BeatSaberMultiplayerServerRepo

**Comment by JBSTheGamer** [comment]
ok thanks will do

**Comment by JBSTheGamer** [comment]
Also one more thing what tickrate would you suggest?

**Comment by Zingabopp** [comment]
I actually don't know much about the ServerHub side of things, try asking in the BSMG Discord multiplayer channel. There's several ServerHub operators there.

**Comment by JBSTheGamer** [comment]
ok
